#!/bin/bash

# Génère le contenu statique
npm run generate

# Ajoute le dossier dist
git add dist

# Valide les changements
git commit -m "Mettre à jour le contenu généré"

# Pousse les changements vers la branche par défaut (master)
git subtree push --prefix dist origin master
